import '@/styles/global.css'
import { Inter } from 'next/font/google'
import Provider from '@/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
}

const RootLayout: React.FC <Props> = ({children}) =>{
  return (
    <html lang="en">
      <body><Provider>{children}</Provider></body>
    </html>
  )
}

export default RootLayout