import { SignUpContainer } from "@/containers";

// Seo
export const metadata = {
  title: 'Kayıt Ol',
  description: 'Generated by create next app',
}

const SignUp: React.FC = () => {
  return <main><SignUpContainer/></main>;
};

export default SignUp;