import { LoginContainer } from "@/containers";

// Seo
export const metadata = {
  title: 'Giriş Yap',
  description: 'Generated by create next app',
}

const Login: React.FC = () => {
  return <main><LoginContainer/></main>;
};

export default Login;